<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionsSeeder extends Seeder
{
    public function run(): void
    {
        // position_type_id: 1 = สายวิชาการ, 2 = สายสนับสนุน
        $positions = [
            ['name' => 'อาจารย์', 'position_type_id' => 1],
            ['name' => 'ผู้ช่วยศาสตราจารย์', 'position_type_id' => 1],
            ['name' => 'รองศาสตราจารย์', 'position_type_id' => 1],
            ['name' => 'ศาสตราจารย์', 'position_type_id' => 1],
            ['name' => 'เจ้าพนักงานตรวจสอบบัญชี', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่เทคนิค', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่เทคนิคโสตทัศนูปกรณ์', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่เทคนิคการเงินและบัญชี', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่เทคนิคปฏิบัติการคอมพิวเตอร์', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่เทคนิคปฏิบัติการสิ่งแวดล้อม', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ในโครงการยุทธศาสตร์มหาวิทยาลัยราชภัฏ', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ซ่อมบำรุงเครื่องปรับอากาศ', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ทั่วไป', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ธุรการ', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ธุรการการเงิน', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ธุรการบัญชี', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่บริหารงานทั่วไป', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ปฏิบัติการทั่วไป', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ปฏิบัติการสนาม', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ปฏิบัติการอาคาร', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่ปะปา', 'position_type_id' => 2],
            ['name' => 'เจ้าหน้าที่รักษาความปลอดภัย', 'position_type_id' => 2],
            ['name' => 'คนสวน', 'position_type_id' => 2],
            ['name' => 'ครู', 'position_type_id' => 1],
            ['name' => 'ครูอาสาสมัครชาวจีน', 'position_type_id' => 2],
            ['name' => 'ช่างเครื่องคอมพิวเตอร์', 'position_type_id' => 2],
            ['name' => 'ช่างเทคนิค', 'position_type_id' => 2],
            ['name' => 'ช่างไฟฟ้า', 'position_type_id' => 2],
            ['name' => 'ช่างไม้', 'position_type_id' => 2],
            ['name' => 'ช่างพิมพ์', 'position_type_id' => 2],
            ['name' => 'ที่ปรึกษางานคลัง', 'position_type_id' => 2],
            ['name' => 'นักเอกสารสนเทศ', 'position_type_id' => 1],
            ['name' => 'นักจัดการงานทั่วไป', 'position_type_id' => 2],
            ['name' => 'นักทรัพยากรบุคคล', 'position_type_id' => 2],
            ['name' => 'นักประชาสัมพันธ์', 'position_type_id' => 2],
            ['name' => 'นักวิเคราะห์นโยบายและแผน', 'position_type_id' => 1],
            ['name' => 'นักวิจัย', 'position_type_id' => 1],
            ['name' => 'นักวิชาการเกษตร', 'position_type_id' => 1],
            ['name' => 'นักวิชาการเงินและบัญชี', 'position_type_id' => 1],
            ['name' => 'นักวิชาการโภชนาการ', 'position_type_id' => 1],
            ['name' => 'นักวิชาการโสตทัศนศึกษา', 'position_type_id' => 1],
            ['name' => 'นักวิชาการการเงินและบัญชี', 'position_type_id' => 1],
            ['name' => 'นักวิชาการคอมพิวเตอร์', 'position_type_id' => 1],
            ['name' => 'นักวิชาการตรวจสอบภายใน', 'position_type_id' => 1],
            ['name' => 'นักวิชาการนโยบายและแผน', 'position_type_id' => 1],
            ['name' => 'นักวิชาการนักศึกษา', 'position_type_id' => 1],
            ['name' => 'นักวิชาการนิติกร', 'position_type_id' => 1],
            ['name' => 'นักวิชาการประกันคุณภาพ', 'position_type_id' => 1],
            ['name' => 'นักวิชาการพัสดุ', 'position_type_id' => 1],
            ['name' => 'นักวิชาการศึกษา', 'position_type_id' => 1],
            ['name' => 'นักวิชาการศึกษา (งานประกันคุณภาพ)', 'position_type_id' => 1],
            ['name' => 'นักวิชาการศึกษา (งานภาษาต่างประเทศ)', 'position_type_id' => 1],
            ['name' => 'นักวิชาการสาธารณสุข', 'position_type_id' => 1],
            ['name' => 'นักวิทยาศาสตร์', 'position_type_id' => 1],
            ['name' => 'นิติกร', 'position_type_id' => 1],
            ['name' => 'บรรณารักษ์', 'position_type_id' => 1],
            ['name' => 'บุคลากร', 'position_type_id' => 2],
            ['name' => 'ผู้ช่วยและอำนวยความสะดวกฝึกทักษะทางภาษา', 'position_type_id' => 2],
            ['name' => 'ผู้ปฏิบัติงานโภชนาการ', 'position_type_id' => 2],
            ['name' => 'ผู้ปฏิบัติงานโสตทัศนศึกษา', 'position_type_id' => 2],
            ['name' => 'ผู้ปฏิบัติงานบริหาร', 'position_type_id' => 2],
            ['name' => 'ผู้ปฏิบัติงานห้องสมุด', 'position_type_id' => 2],
            ['name' => 'ผู้อำนวยการกองกลาง', 'position_type_id' => 2],
            ['name' => 'ผู้อำนวยการกองนโยบายและแผน', 'position_type_id' => 2],
            ['name' => 'ผู้อำนวยการกองบริการการศึกษา', 'position_type_id' => 2],
            ['name' => 'ผู้อำนวยการสถาบันวิจัยและพัฒนา', 'position_type_id' => 2],
            ['name' => 'ผู้อำนวยการสำนักงานอธิการบดี', 'position_type_id' => 2],
            ['name' => 'พนักงานขับรถยนต์', 'position_type_id' => 2],
            ['name' => 'พนักงานทั่วไป', 'position_type_id' => 2],
            ['name' => 'พนักงานทั่วไป (ดูแลความสะอาดอาคาร)', 'position_type_id' => 2],
            ['name' => 'พนักงานทั่วไป (ดูแลความสะอาดอาคารและห้องเรียน)', 'position_type_id' => 2],
            ['name' => 'พนักงานบริการเอกสารทั่วไป', 'position_type_id' => 2],
            ['name' => 'พนักงานพิมพ์', 'position_type_id' => 2],
            ['name' => 'พนักงานรักษาความปลอดภัย', 'position_type_id' => 2],
            ['name' => 'พนักงานสถานที่', 'position_type_id' => 2],
            ['name' => 'พนักงานห้องปฏิบัติการ', 'position_type_id' => 2],
            ['name' => 'พยาบาล', 'position_type_id' => 1],
            ['name' => 'วิศวกร', 'position_type_id' => 1],
            ['name' => 'วิศวกรโยธา', 'position_type_id' => 1],
            ['name' => 'วิศวกรไฟฟ้า', 'position_type_id' => 1],
            ['name' => 'สถาปนิก', 'position_type_id' => 1],
            ['name' => 'หัวหน้าสำนักงานคณบดีคณะเทคโนโลยีอุตสาหกรรม', 'position_type_id' => 2],
            ['name' => 'หัวหน้าสำนักงานคณบดีคณะมนุษยศาสตร์และสังคมศาสตร์', 'position_type_id' => 2],
            ['name' => 'หัวหน้าสำนักงานคณบดีคณะวิทยาการจัดการ', 'position_type_id' => 2],
            ['name' => 'หัวหน้าสำนักงานสถาบันวิจัยและพัฒนา', 'position_type_id' => 2],
            ['name' => 'หัวหน้าสำนักงานสำนักวิทยบริการและเทคโนโลยีสารสนเทศ', 'position_type_id' => 2],
        ];

        DB::table('positions')->insertOrIgnore($positions);
    }
}
