<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Http\Resources\ProposalResource; use App\Models\Proposal; use App\Services\{AuditService,NotificationDeliveryService}; use App\Support\ApiPagination; use Illuminate\Http\Request;
class ProposalController extends Controller {
 private AuditService $audit; private NotificationDeliveryService $notify;
 public function __construct(AuditService $audit,NotificationDeliveryService $notify){$this->audit=$audit;$this->notify=$notify;}
 private function rules(bool $update=false){return ['title'=>[$update?'sometimes':'required','string','max:255'],'summary'=>['nullable','string'],'year'=>[$update?'sometimes':'required','digits:4'],'budget'=>['nullable','numeric','min:0'],'status'=>['sometimes','in:draft,submitted,approved,rejected']];}
 public function index(Request $r){$v=$r->validate(['scope'=>'sometimes|in:mine,all','q'=>'nullable|string','status'=>'nullable|string','year'=>'nullable|digits:4','per_page'=>'sometimes|integer|min:1|max:100']);$q=Proposal::query();if(($v['scope']??'mine')==='mine')$q->where('owner_user_id',$r->user()->id);$q->when($v['q']??null,fn($x,$s)=>$x->where('title','like',"%$s%"))->when($v['status']??null,fn($x,$s)=>$x->where('status',$s))->when($v['year']??null,fn($x,$s)=>$x->where('year',$s));$p=$q->latest()->paginate($v['per_page']??20);return ApiPagination::response($p,ProposalResource::collection($p->getCollection()));}
 public function store(Request $r){$d=$r->validate($this->rules());$d['owner_user_id']=$r->user()->id;$d['status']=$d['status']??'draft';$m=Proposal::create($d);$this->audit->record($r,'create',$m);return (new ProposalResource($m))->response()->setStatusCode(201);}
 public function show(Request $r,Proposal $proposal){$this->authorize('view',$proposal);return new ProposalResource($proposal);}
 public function update(Request $r,Proposal $proposal){$this->authorize('update',$proposal);$before=$proposal->toArray();$d=$r->validate($this->rules(true));if(isset($d['status'])&&in_array($d['status'],['approved','rejected'])&&!$r->user()->isAdmin())abort(403);$old=$proposal->status;$proposal->update($d);$this->audit->record($r,'update',$proposal,$before);if($old!==$proposal->status&&in_array($proposal->status,['approved','rejected']))$this->notify->deliverToUser($proposal->owner,'สถานะข้อเสนอเปลี่ยนแล้ว',$proposal->title,'proposal_status',['entity_type'=>'proposal','entity_id'=>$proposal->id,'route'=>'/proposals/'.$proposal->id]);return new ProposalResource($proposal);}
 public function destroy(Request $r,Proposal $proposal){$this->authorize('delete',$proposal);$before=$proposal->toArray();$proposal->delete();$this->audit->record($r,'delete',$proposal,$before);return response()->json(['message'=>'ลบสำเร็จ']);}
}
