<?php

return [
    'base_url'      => env('SSO_BASE_URL', 'http://localhost:8000'),
    'driver'        => env('SSO_DRIVER', 'oauth'),
    'expert_api_base_url' => env('SSO_EXPERT_API_BASE_URL', 'https://expert.uru.ac.th/api'),
    'expert_api_token' => env('SSO_EXPERT_API_TOKEN'),
    'client_id'     => env('SSO_CLIENT_ID'),
    'client_secret' => env('SSO_CLIENT_SECRET'),
    'redirect_uri'  => env('SSO_REDIRECT_URI', env('APP_URL') ? rtrim(env('APP_URL'), '/') . '/auth/callback' : null),
    'mock'          => env('SSO_MOCK', false),
    'mock_routes'   => env('SSO_MOCK_ROUTES', false),
    'fast_mock'     => env('SSO_FAST_MOCK', false),
    'local_database' => env('SSO_LOCAL_DATABASE', false),
    'mock_email'    => env('SSO_MOCK_EMAIL', 'phanuwat@live.uru.ac.th'),
    'mock_password' => env('SSO_MOCK_PASSWORD', 'password'),
    'mock_accounts' => [
        [
            'id' => 900304,
            'code' => '205234-304',
            'username' => '3530900177802',
            'email' => 'mr.phanuwat@gmail.com',
            'password' => 'password',
            'citizen_id' => '3530900177802',
            'prefix_th' => 'นาย',
            'first_name_th' => 'ภานุวัฒน์',
            'last_name_th' => 'ขันจา',
            'prefix_en' => 'Mr.',
            'first_name_en' => 'Phanuwat',
            'last_name_en' => 'khanwat',
            'type' => 'TEACHER',
            'degree' => 'MASTER',
            'gender' => 'MALE',
            'status' => 'ACTIVE',
            'nationality' => 'THAI',
            'faculty_id' => 5,
            'faculty_name_th' => 'คณะเทคโนโลยีอุตสาหกรรม',
            'faculty_name_en' => 'คณะเทคโนโลยีอุตสาหกรรม',
            'department_id' => 122,
            'department_name_th' => 'หลักสูตรวิศวกรรมบัณฑิต',
            'department_name_en' => 'หลักสูตรวิศวกรรมบัณฑิต',
            'study_year' => 0,
            'nickname' => '',
            'picture' => 'https://hrms.uru.ac.th/WebURUINF/Applications/File/Forms/frmFileStorage?guid=46407332252C4D439A5383C2A07257EA',
            'picture_base64' => '',
            'birth_date' => '1980-04-10',
            'last_updated_at' => '2026-04-07 06:12:29',
            'teacher' => [],
            'study' => [],
            'custom1' => null,
            'custom2' => null,
            'custom3' => null,
            'campus_id' => 1,
            'curriculum_id' => 0,
            'passport_id' => '',
        ],
        [
            'id' => 2174,
            'code' => '205234',
            'username' => 'phanuwat',
            'email' => env('SSO_MOCK_EMAIL', 'phanuwat@live.uru.ac.th'),
            'password' => env('SSO_MOCK_PASSWORD', 'password'),
            'citizen_id' => '3530900177802',
            'prefix_th' => 'นาย',
            'first_name_th' => 'ภานุวัฒน์',
            'last_name_th' => 'ขันจา',
            'first_name_en' => 'Phanuwat',
            'last_name_en' => 'Khanwat',
            'picture' => 'https://hrms.uru.ac.th/WebURUINF/Applications/File/Forms/frmFileStorage?guid=46407332252C4D439A5383C2A07257EA',
        ],
        [
            'id' => 2175,
            'code' => '205235',
            'username' => 'somsak',
            'email' => env('SSO_MOCK_USER2_EMAIL', 'somsak@gmail.com'),
            'password' => env('SSO_MOCK_USER2_PASSWORD', 'password'),
            'citizen_id' => '1111111111111',
            'prefix_th' => 'นาย',
            'first_name_th' => 'สมศักดิ์',
            'last_name_th' => 'ทดสอบ',
            'first_name_en' => 'Somsak',
            'last_name_en' => 'Test',
        ],
        [
            'id' => 2180,
            'code' => '205240',
            'username' => 'mockuser01',
            'email' => 'mockuser01@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111101',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User01',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User01',
        ],
        [
            'id' => 2181,
            'code' => '205241',
            'username' => 'mockuser02',
            'email' => 'mockuser02@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111102',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User02',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User02',
        ],
        [
            'id' => 2182,
            'code' => '205242',
            'username' => 'mockuser03',
            'email' => 'mockuser03@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111103',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User03',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User03',
        ],
        [
            'id' => 2183,
            'code' => '205243',
            'username' => 'mockuser04',
            'email' => 'mockuser04@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111104',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User04',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User04',
        ],
        [
            'id' => 2184,
            'code' => '205244',
            'username' => 'mockuser05',
            'email' => 'mockuser05@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111105',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User05',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User05',
        ],
        [
            'id' => 2185,
            'code' => '205245',
            'username' => 'mockuser06',
            'email' => 'mockuser06@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111106',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User06',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User06',
        ],
        [
            'id' => 2186,
            'code' => '205246',
            'username' => 'mockuser07',
            'email' => 'mockuser07@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111107',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User07',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User07',
        ],
        [
            'id' => 2187,
            'code' => '205247',
            'username' => 'mockuser08',
            'email' => 'mockuser08@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111108',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User08',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User08',
        ],
        [
            'id' => 2188,
            'code' => '205248',
            'username' => 'mockuser09',
            'email' => 'mockuser09@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111109',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User09',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User09',
        ],
        [
            'id' => 2189,
            'code' => '205249',
            'username' => 'mockuser10',
            'email' => 'mockuser10@gmail.com',
            'password' => 'password',
            'citizen_id' => '1111111111110',
            'prefix_th' => 'นาย',
            'first_name_th' => 'Mock',
            'last_name_th' => 'User10',
            'first_name_en' => 'Mock',
            'last_name_en' => 'User10',
        ],
    ],
];
